var keyMirror = require('keymirror');

module.exports = keyMirror({
  TODO_CREATE: null,
  TODO_CREATE_FAILED: null,
  TODO_COMPLETE: null,
  TODO_DESTROY: null,
  TODO_DESTROY_CANCEL: null,
  TODO_DESTROY_COMPLETED: null,
  TODO_DESTROY_COMPLETED_REQUEST: null,
  TODO_DESTROY_COMPLETED_CANCEL: null,
  TODO_TOGGLE_COMPLETE_ALL: null,
  TODO_UNDO_COMPLETE: null,
  TODO_UPDATE_TEXT: null,
  TODO_UPDATE_TEXT_SUCCESS: null,
  TODO_UPDATE_TEXT_CANCEL: null,
  TODO_RECEIVE_RAW_ALL: null,
  TODO_CREATE_ERROR: null,
  TODO_DESTROY_ERROR: null,
  TODO_DESTROY_ALL_ERROR: null
});